# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo on source_branch
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          # <<recommended if project uses git submodules for any purpose>>
          # <<required if deploying to git submodule directory>>
          fetch-depth: '0'
          # <<fetch-depth: '0' currently required until shallow clone problems are solved>>

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          set -ex
          sudo apt update
          sudo snap install aws-cli --classic
          wget https://github.com/gohugoio/hugo/releases/download/v0.138.0/hugo_extended_withdeploy_0.138.0_linux-amd64.tar.gz
          mkdir ~/bin
          tar -xf hugo_extended_withdeploy_0.138.0_linux-amd64.tar.gz -C ~/bin
          sudo chmod +x ~/bin
          
          ~/bin/hugo version
          ~/bin/hugo
          ~/bin/hugo deploy
